# One-off data prep script — not part of the app. Reads the two xlsx
# files the user downloaded from data.go.kr / Seoul Open Data Plaza,
# geocodes the addresses that lack coordinates, and writes a SQL file
# of INSERT statements to run once in the Supabase SQL Editor.
import time
import requests
import pandas as pd

NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
HEADERS = {"User-Agent": "silverlife-import-script/1.0 (one-off data prep)"}


def geocode(address: str):
    try:
        resp = requests.get(
            NOMINATIM_URL,
            params={"q": address, "format": "json", "limit": 1},
            headers=HEADERS,
            timeout=10,
        )
        results = resp.json()
        if results:
            return float(results[0]["lat"]), float(results[0]["lon"])
    except Exception as e:
        print(f"  geocode failed for {address!r}: {e}")
    return None, None


def sql_escape(value) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


rows = []  # (name, address, lat, lng, category, telephone)

# --- 경로당 (already has lat/lng) ---
df_gyerodang = pd.read_excel("전국마을회관및경로당표준데이터.xlsx")
for _, r in df_gyerodang.iterrows():
    if r["시설유형"] != "경로당":
        continue
    rows.append((
        r["시설명"],
        r["소재지도로명주소"] if pd.notna(r["소재지도로명주소"]) else r["소재지지번주소"],
        r["위도"],
        r["경도"],
        "경로당",
        r["전화번호"] if pd.notna(r["전화번호"]) else None,
    ))

print(f"경로당: {len(rows)}건 (좌표 이미 있음)")

# --- 노인복지관 (needs geocoding) ---
df_bokji = pd.read_excel("서울시 사회복지시설(노인여가복지시설) 목록.xlsx")
df_bokji = df_bokji[df_bokji["시설종류명(시설유형)"] == "(노인여가복지시설) 노인복지관"]

print(f"노인복지관: {len(df_bokji)}건, 지오코딩 시작 (89건, 약 90초 소요)")
geocoded = 0
skipped = 0
for i, r in df_bokji.iterrows():
    address = r["시설주소"]
    lat, lng = geocode(address)
    time.sleep(1)  # Nominatim usage policy: max 1 request/sec
    if lat is None:
        skipped += 1
        print(f"  스킵 (좌표 못 찾음): {r['시설명']} / {address}")
        continue
    rows.append((r["시설명"], address, lat, lng, "복지관", None))
    geocoded += 1

print(f"노인복지관: {geocoded}건 지오코딩 성공, {skipped}건 스킵")
print(f"총 {len(rows)}건")

# --- write SQL ---
with open("supabase/import_facilities.sql", "w", encoding="utf-8") as f:
    f.write("-- Generated by import_facilities.py — run once in the SQL Editor.\n")
    f.write("-- Seoul 경로당 (1615건) + 노인복지관 (지오코딩 완료) 데이터 일괄 삽입.\n\n")
    batch_size = 200
    for start in range(0, len(rows), batch_size):
        batch = rows[start:start + batch_size]
        f.write("insert into public.facilities (name, address, lat, lng, category, telephone) values\n")
        values_lines = []
        for name, address, lat, lng, category, telephone in batch:
            values_lines.append(
                f"  ({sql_escape(name)}, {sql_escape(address)}, {lat}, {lng}, "
                f"{sql_escape(category)}, {sql_escape(telephone)})"
            )
        f.write(",\n".join(values_lines))
        f.write("\non conflict (name, address) do nothing;\n\n")

print("Wrote supabase/import_facilities.sql")
